#
# Copyright (C) 2024 Bobby
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bobby-ttyd
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for ttyd By Bobby
LUCI_DESCRIPTION:=LuCI support for ttyd By Bobby
LUCI_DEPENDS:=+ttyd
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
