#
# Copyright (C) 2021 Bobby
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bobby-aliyundrive-webdav
PKG_VERSION:=1.10.6
PKG_RELEASE:=1


LUCI_TITLE:=LuCI support for aliyundrive-webdav By Bobby
LUCI_DESCRIPTION:=LuCI interface for AliyunDrive-WebDAV By Bobby
LUCI_DEPENDS:=+aliyundrive-webdav
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
